title: learnlatex.org
description: Learn LaTeX online

repository: learnlatex/learnlatex.github.io

plugins:
  - jekyll-sitemap

kramdown:
    syntax_highlighter_opts:
      disable: true

sass:
    style: compressed

latex: "<span>L<span style='font-variant: small-caps; vertical-align:.35ex;margin-left:-.15em;margin-right:-.05em;'>a</span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
tex: "<span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"





# LANGUAGES 
# Settings for multilingual set up (in alphabetical order)
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      label: "English"
      layout: "learnlatex"
  - 
    scope:
      path: "es"
    values:
      lang: "es"
      label: "Español"
      layout: "learnlatex"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
      label: "Français"
      layout: "learnlatex"
  -
    scope:
      path: "de"
    values:
      lang: "de"
      label: "German"
      layout: "learnlatex"
  -
    scope:
      path: "pt"
    values:
      lang: "pt"
      label: "Português"
      layout: "learnlatex"
  -
    scope:
      path: "vi"
    values:
      lang: "vi"
      label: "Tiếng Việt"
      layout: "learnlatex"
  -
    scope:
      path: "ja"
    values:
      lang: "ja"
      label: "日本人"
      layout: "learnlatex"

# FIXME: May not be needed anymore, succeeded by _data/languages.yml
# Languages selectable in front-end language selection drop down
languages:
  - en
  - es
  - fr
  - pt
  - vi





# EXCLUSIONS
# Exclude from Jekyll processing (in alphabetical order)
# https://jekyllrb.com/docs/configuration/options/
exclude:
  - .ruby-version
  - example.json
  - example.yaml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
