# CONFIGURATION
# https://jekyllrb.com/docs/configuration/options/

title: learnlatex.org
description: Learn LaTeX online
repository: learnlatex/learnlatex.github.io

plugins:
  - jekyll-sitemap

kramdown:
    syntax_highlighter_opts:
      disable: true

sass:
    style: compressed

limit_posts: 0

latex: "<span>L<span style='font-variant: small-caps; vertical-align:.35ex;margin-left:-.15em;margin-right:-.05em;'>a</span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"
tex: "<span>T<span style='text-transform:uppercase; vertical-align:-.4ex;margin-left:-.1em;'>e</span>X</span>"


# LANGUAGES, LABELS, LAYOUTS
# Settings for multilingual set up: 
# In alphabetical order by language code.
# In ascending order by path specifity.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "en"
    values:
      lang: "en"
      label: "English"
  -
    scope:
      path: "es"
    values:
      lang: "es"
      label: "Español"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
      label: "Français"
  -
    scope:
      path: "de"
    values:
      lang: "de"
      label: "German"
  -
    scope:
      path: "pt"
    values:
      lang: "pt"
      label: "Português"
  -
    scope:
      path: "vi"
    values:
      lang: "vi"
      label: "Tiếng Việt"
  -
    scope:
      path: "ja"
    values:
      lang: "ja"
      label: "日本語"
  -
    scope:
      path: "zh"
    values:
      lang: "zh"
      label: "中文"
