# CONFIGURATION
# https://jekyllrb.com/docs/configuration/options/

title: learnlatex.org
description: Learn LaTeX online
repository: learnlatex/learnlatex.github.io


# PLUGINS
# https://jekyllrb.com/docs/plugins/
plugins:
  - jekyll-sitemap

kramdown:
    syntax_highlighter_opts:
      disable: true

sass:
    style: compressed


# POST LIMIT
# Limit the number of posts to parse and publish.
# https://jekyllrb.com/docs/configuration/options/
limit_posts: 0


# LANGUAGES, LABELS, LAYOUTS
# Settings for multilingual set up: 
# In alphabetical order by language code.
# In ascending order by path specifity.
# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
      layout: "home"
  -
    scope:
      path: "en"
    values:
      lang: "en"
      label: "English"
      layout: "default"
  -
    scope:
      path: "es"
    values:
      lang: "es"
      label: "Español"
      layout: "default"
  -
    scope:
      path: "fr"
    values:
      lang: "fr"
      label: "Français"
      layout: "default"
  -
    scope:
      path: "de"
    values:
      lang: "de"
      label: "German"
      layout: "default"
  -
    scope:
      path: "pt"
    values:
      lang: "pt"
      label: "Português"
      layout: "default"
  -
    scope:
      path: "vi"
    values:
      lang: "vi"
      label: "Tiếng Việt"
      layout: "default"
  -
    scope:
      path: "ja"
    values:
      lang: "ja"
      label: "日本語"
      layout: "default"
  -
    scope:
      path: "zh"
    values:
      lang: "zh"
      label: "中文"
      layout: "default"
